# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: macOS-12 

steps:
- script: system_profiler SPSoftwareDataType SPHardwareDataType
  displayName: 'Run a one-line script'

